# This workflow will install the dependencies and then build and deploy the
# TypeScript documentation website to the docs branch.

name: Publish Documentation

on:
  push:
    branches:
      - master

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install NPM dependencies
        run: npm ci

      - name: Generate docs
        run: npm run doc

      - name: Publish generated docs to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs
          branch: docs
          token: ${{ secrets.ACCESS_TOKEN }}
